CREATE DATABASE HYCM17032024;
use HYCM17032024;

CREATE TABLE FacturaVentas(
Id INT PRIMARY KEY IDENTITY(1,1),
FechaVenta DATE NOT NULL,
Correlativo VARCHAR(100) NOT NULL,
Cliente VARCHAR(100) NOT NULL,
TotalVenta DECIMAL(10,2) NOT NULL,
);
GO

CREATE TABLE DetFacturaVentas(
Id INT PRIMARY KEY IDENTITY (1,1),
IdFactuVenta INT NOT NULL,
Producto VARCHAR(100) NOT NULL,
Cantidad INT,
PrecioUnitario DECIMAL(10,2),
FOREIGN KEY (IdFactuVenta) REFERENCES FacturaVentas(Id) ON DELETE CASCADE
);
GO

